### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by Redns** [SuessLabs/VsLinuxDebug#32]
Hey, thank you very much for developing this plugin. I have encountered some problems in the process of using it and I hope to get your help. Here is my Linux system information and I have followed the tutorial to install dotnet、openssh-server and curl
```bash
Linux VM-0-16-ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
And this is the error message
![image](https://user-images.githubusercontent.com/69022576/169322148-2de4db85-2e21-4eba-aee9-5a0abdfc3a0e.png)

The console output
![image](https://user-images.githubusercontent.com/69022576/169322322-b6cc12d4-5757-48f4-b195-6cac3d75b9b3.png)

The code is compiled locally.

**Comment by DamianSuess** [comment]
From the looks of it, you have a solid connection and it uploaded/decompressed your project which is great.

This is a known issue w/ remote debugging and unfortunately Microsoft's VSDbg doesn't provide much documentation or feedback other than _failing to launch_.  I have seen firewall issues in the past blocking port access (_see 'Additional Resources' below_). Also, I've had success debugging console apps on Ubuntu 20.04, but issues on 22.04.

To try and help you out:
* Which version of Ubuntu are you using?
* Are you able to manually launch and Attach to Process via `VS > Debug > Attach to Process...`?

Additional Resources:
* [Remote Debugger Port Assignments](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2022)
* [Remote Debugging](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022)

**Comment by TGlev** [comment]
Sorry for reopening this issue, but I'm having this exact issue but on the latest version of raspbian instead...

My console output looks exactly like the one provided by the original author and the error popup I get is also the same.
I have allowed the VS2022 port (4026) trough the firewall on the pi. I have also made sure the app is configured for remote debugging.

I can attach to the process via VS > Debug > Attach To Process, works just fine. I have also tried adding:
var _ = Console.ReadLine();

As the first line in my Main();

None of these options have been able to resolve my problem. Any more suggestions?

**Comment by TGlev** [comment]
After some more digging I found this in the debug adapter host log:
`ERROR: Debug adapter error output: bash: line 1: /home/retina/.vs-debugger/vs2022: Is a directory`

However, I do not understand how to fix this... :)

**Comment by TGlev** [comment]
If I change the launch json adapterArgs -T argument from:
~/.vsdbg/vs2022 
to
~/.vsdbg/vs2022

and then launch the debug manually with the command window and command:
DebugAdapterHost.Launch /LaunchJson:"path-to-launch.json" /EngineGuid:541B8A8A-6081-4506-9F0A-1CE771DEBC04

it seems to get further... Seems to me, but Im not sure, that the exported path to vsdbg is incorrect in my launch.json.

**Comment by DamianSuess** [comment]
thank you @TGlev, reopening this issue

**Comment by TGlev** [comment]
> thank you @TGlev, reopening this issue. If you have time, please feel free to jump in to address this issue. Unfortunately, been known to be temperamental between environment-to-environment.

Thanks. Im afraid my knowledge doesnt include visual studio extensions. Havent been able to figure much out regarding this issue on my own.
