### ISSUE TITLE
[2.0] Disable the switching of tabs during build

### ISSUE THREAD

**Issue by HakanL** [SuessLabs/VsLinuxDebug#42]
Whenever I'm building my solution VS2022 is always switching to the "Linux Debugger" output, which is very annoying, since I want to see the build output as it has all the details. I just want the Linux Debugger output when I'm actually deploying to the linux device.

**Comment by DamianSuess** [comment]
@HakanL,

Thank you for the feature request, I can see how that can be non-favorable for those preferring the base build output instead.

If you haven't already, I can look into making this into an editable option for v2.0.

**Comment by HakanL** [comment]
Editable option would be great!
