### ISSUE TITLE
Confusion log entries in "

### ISSUE THREAD

**Issue by HakanL** [SuessLabs/VsLinuxDebug#52]
**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'
4. Error message '...'

**Expected behavior**

**Screenshots**

**Linux Distribution:**
 - OS: [e.g. Ubuntu, Debian, ...]
 - Version [e.g. 20.04 LTS, 22.04 LTS, ...]

**Additional context**

**Comment by DamianSuess** [comment]
I assume #53 is the real issue report?

**Comment by HakanL** [comment]
Oh sorry, I must've fat-fingered the post button :)
