### ISSUE TITLE
SSH Key Login with ssh-rsa not possible[Issue] 

### ISSUE THREAD

**Issue by zeusware** [SuessLabs/VsLinuxDebug#61]
See:
https://github.com/sshnet/SSH.NET/issues/956
https://github.com/sshnet/SSH.NET/issues/825#issuecomment-1139440419

Workaround:
A simple solution.

Add this line in /etc/ssh/sshd_config.

PubkeyAcceptedAlgorithms +ssh-rsa
Afterwards, restart the sshd service to make the new settings come into effect.

$ sudo systemctl restart sshd
From:
https://unix.stackexchange.com/questions/721606/ssh-server-gives-userauth-pubkey-key-type-ssh-rsa-not-in-pubkeyacceptedalgorit

**Comment by DamianSuess** [comment]
@zeusware with your PR #62, this can be closed now, correct?

**Comment by zeusware** [comment]
correct :)
