### ISSUE TITLE
[Enhancement] Deploy only Diff

### ISSUE THREAD

**Issue by zeusware** [SuessLabs/VsLinuxDebug#64]
## Description
If using many nuget packages at a project, the tar 'complete' project folder and transport it, unpack it, is quite time intensive.

In VS u have normaly the Commands
(i use german, so sorry if the translation is incorrect, but i guess u know waht i mean)

- Clean Project
- Clean Solution
- Build Project
- Re-Build Project
- Build Solution
- Re-Build Solution

on such Re-Build task it is not necessary to transport the whole stuff. 

## Options
B4 Re-Build iterate and Cache the FileInfo's with path, name and TimeStamp
After Re-Build check what's changed in the local build folder (compare with new iteration)
Just copy/delete to target the modificated files.

With best regards

**Comment by DamianSuess** [comment]
Duplicate of #45. Let's make this happen. I too feel the pain, especially over a slow VPN 👍

**Comment by DamianSuess** [comment]
Closing as duplicate of #45
