### ISSUE TITLE
[Enhancement] Start debugging with sudo

### ISSUE THREAD

**Issue by smint80** [SuessLabs/VsLinuxDebug#77]
## Description
I would be very nice to be able to start the debugging session with sudo when developing software that need to be run with admin rights. Often that ise the case when developing systemd services.

Right now I have to use the build and deploy and the use the DebugAdapterHost.Launch manually from the command window to do that. The only thing different from the generated launch.json and my manually written launch.json that works is the adapter args.

Generated: -ssh -pw password user@host -T  ~/vsdbg/vs2022/vsdbg  --engineLogging=./VSLinuxDbg/Application/_vsdbg.log
Needed: -ssh -pw password user@host -batch -T sudo ~/vsdbg/vs2022/vsdbg  --engineLogging=./VSLinuxDbg/Application/_vsdbg.log

It would be nice to implement an option for this.

**Comment by DamianSuess** [comment]
There aren't any plans to include `sudo` just yet. However, don't be discouraged, your suggested feature may appear in a future release once the advanced settings dialog that will be implemented in the near future.

Until then, I suggest that your application execute elevated procedures when necessary versus the entire application if possible. I can dig up a sample of this if you'd like.
