### ISSUE TITLE
[Enhancement] Setting environment

### ISSUE THREAD

**Issue by smint80** [SuessLabs/VsLinuxDebug#78]
## Description
It would be nice if a DOTNET_ENVIRONMENT could be set to remote debug with different profiles.
Only thing needed in launch.json to support this is in the configuration where this could be added:

```
"env": {
  "DOTNET_ENVIRONMENT": "Development"
}
```

**Comment by DamianSuess** [comment]
Interesting suggestion. This may be a good candidate for the new connection settings profiles feature. Sprinkle on a little user-customized settings versus the default ones
