### ISSUE TITLE
[Issue] VSLinuxDebug no more working after recent VS updates

### ISSUE THREAD

**Issue by massimoappi-asacsrl** [SuessLabs/VsLinuxDebug#79]
Hello, thanks for this great tool!

I noticed that starting from latest VS upgrades (last month) the tool is not working anymore.

When I do Extensions/Linux Debugger/Build and Deploy, on the "Linux Debugger" output window, after the "Build was successful" I get the error message "An error occurred during the build process. Unable to find method 'Void Renci.SshNet.PrivateKeyAuthenticationMethod..ctor(System.String, Renci.SshNet.PrivateKeyFile[])'"

It's crear to me thas something changed from the VS environment side, not from the tool side, because the problems started after a VS update. I already tried to uninstall/reinstall plugin, but nothing changed.

So I cloned the project to my PC, opened the solution in VS, updated all the NuGet packages, including the SSH.NET to the version 2024.0.0 (wich is the component I mind is raising the above error).

After the update some code started to not compile anymore.. but with a few corrections and a comment-out of

```
  public static void SetupConnection(ConnectionInfo connection)
  {
    //connection.HostKeyAlgorithms[RSA_SHA2_256] = data => new KeyHostAlgorithm(RSA_SHA2_256, new RsaKey(), data);
  }

```
(I don't know how to correct), the project now compile well, and the new .vsix package now works well and the Build and Deploy is successfully (also the debug!!)

Please, update the NuGet packages, correct the commented code (I'm not an expert in this) and release a new tools version for everyone's interested!

Thanks

**Comment by DamianSuess** [comment]
Thank you for bringing this to my attention!

Just to make sure, which version of Visual Studio are you using? This way I can attempt to version match. Currently, I'm still running on v17.8.6

> Help > About Microsoft Visual Studio

**Comment by massimoappi-asacsrl** [comment]
Here you have all the details:

Microsoft Visual Studio Professional 2022
Versione 17.9.1
VisualStudio.17.Release/17.9.1+34616.47
Microsoft .NET Framework
Versione 4.8.09032
Edizione installata: Professional

on Windows 11 Pro 23H2

**Comment by massimoappi-asacsrl** [comment]
Hello @DamianSuess, any news about the update?

**Comment by DamianSuess** [comment]
Working on it this week 👍

**Comment by massimoappi-asacsrl** [comment]
Tooooooop!! 👍👍👍

**Comment by DamianSuess** [comment]
@massimoappi-asacsrl, preliminary testing is proving to be fruitful.

Going to be doing some final testing before deploying the v2.2 release. Thank you for your patience

**Comment by DamianSuess** [comment]
@massimoappi-asacsrl the latest has been published to VS Marketplace

**Comment by massimoappi-asacsrl** [comment]
Great work @DamianSuess, just updated and it's working like a charm!
Thanks for your precious support!

**Comment by DamianSuess** [comment]
Happy to hear that, you're welcome.

Hope you have a great weekend
