### ISSUE TITLE
SSH Connection error since update 2.2.0

### ISSUE THREAD

**Issue by ghost** [SuessLabs/VsLinuxDebug#82]
## Description
Since the last extension update I cannot use the extension anymore. The code builds fine, but then I get the following error while connecting through SSH:

```
08:37:50.349: Build was successful
08:37:50.371: SSH configuring private key connection...
08:37:50.401: SSH connecting...
08:37:52.091: An error occurred during the build process. La valeur ne peut pas être null.
Nom du paramètre : connectionInfo
08:37:52.091: Failed to perform actions.
```
I updated Visual Studio to the latest version, but it did not help.

## Severity (1-5)
4: Unusable extension, but no crash.

## Steps To Reproduce
1. Click on "Build and Deploy" in the Linux Debugger extension drop-down menu.

## Expected Behavior
SSH upload working as before.

## Configuration:
* **Local OS:** Windows 10 22H2 Build19045.4170
* **Visual Studio:** 2022 64bits Version 17.9.3
* **VS Linux Debugger:** Version 2.2.0
* **Remote OS:** Raspberry Pi 4 with Raspberry Pi OS Lite (64-bit). All packages updated.

## Additional Context
It was working fine two weeks ago. I did not use Visual Studio since.
I am using an SSH key file as credentials (username/password not allowed).
I can connect to my remote device using Putty or powershell with the same SSH key file.

**Comment by ghost** [comment]
I rolled back Visual Studio to 17.8.2 and VS Linux Debugger to 2.1.1 and everything works as expected.

**Comment by DamianSuess** [comment]
Thank you for the additional context, that is a big help. I'll get this on the backlog and try to recreate your scenario when time gets freed up.

If you're feeling adventurous to explore this issue to help speed up, please keep in mind the SSH NuGet package upgrade required by our v2.2.0.

**Comment by stuhugh** [comment]
Here's a patch I wrote that fixed the issue for me.
[fix-ssh-key-access-diff.txt](https://github.com/SuessLabs/VsLinuxDebug/files/14998106/fix-ssh-key-access-diff.txt)

**Comment by DamianSuess** [comment]
Nice @stuhugh!
I'll run this through the test system & get this merged in. On behalf of the other contributors and users, thank you.

**Comment by DamianSuess** [comment]
I'll be publishing a preview release with the changes soon
